### ISSUE TITLE
ESP Sming framework

### ISSUE THREAD

**Issue by robotiko** [mirobot/mirobot-wifi#1]
You might find quite interesting the usage of https://github.com/anakod/Sming since it provides out of the box support to many of the needs.

**Comment by bjpirt** [comment]
Yes, I've come across that. This has been in development since quite a while before it appeared and I haven't looked into porting to it yet. However, the firmware update strategy means there's not a lot of space left so I'm keeping quite tight control over the firmware. Using a framework often results in a bit of bloat unfortunately.

**Comment by robotiko** [comment]
I understand what you mean. 
However OTA update is Supported too ;)

By the way: Terrific project! and very advanced solutions!

**Comment by bjpirt** [comment]
I'm using the rboot bootloader now because it allows me to define where I want to put the partitions more effectively so that I can also squeeze in the web pages and the Arduino firmware so that can be updated over the air too.

Glad you like it!

**Comment by bjpirt** [comment]
I'm currently working on an upgrade mechanism that pulls form Github releases and flashes through the browser. Should be released shortly.
